name: CI

on: [push]

jobs:

  test_only_effdet_backend:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: '3.7'
  
    - name: Test Dependency Support 
      run: |
        pip install pytest
        pip install -e . # The bare layoutparser module 
        pytest tests_deps/test_file_utils.py

    - name: Install only effdet deps 
      run: |
        pip install pytest
        pip install -e ".[effdet]"
        pytest tests_deps/test_only_effdet.py

  test_only_detectron2_backend:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: '3.7'

    - name: Install only Detectron2 deps 
      run: |
        pip install pytest
        pip install -e .
        pip install torchvision && pip install "git+https://github.com/facebookresearch/detectron2.git@v0.5#egg=detectron2"
        pytest tests_deps/test_only_detectron2.py

  test_only_paddledetection_backend:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: '3.7'

    - name: Install only PaddleDetection deps 
      run: |
        pip install pytest
        pip install -e ".[paddledetection]"
        pytest tests_deps/test_only_paddledetection.py

  test_all_methods_all_backends:
    needs: [test_only_effdet_backend, test_only_detectron2_backend, test_only_paddledetection_backend]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7, 3.8]
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install library and dependencies
      run: |
        python -m pip install --upgrade pip
        pip install .
        
    - name: Lint with flake8
      run: |
        pip install flake8
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics --ignore F821
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

    - name: Test with pytest
      run: |
        # Install additional requirements when running tests
        pip install ".[effdet]"
        pip install -r dev-requirements.txt
        pytest tests